apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5173
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.front.name }}
    
